# Generated by Django 2.2.4 on 2019-08-04 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='key_send_on',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
