# Generated by Django 2.2.4 on 2019-08-05 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20190804_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pass_reset_key',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='pass_reset_on',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='activation_key',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
